[package]
name = "chat_sub_converter"
version = "0.1.0"
authors = ["sand49"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
